- hosts: master
  tasks:
    - name: Installing pip
      package:
       name:
         - python3-pip
         - python-pip
  
    - name: Installing essentials
      pip:
        name:
          - openshift
          - PyYAML
    
    - name: Fetching kubeconfig
      fetch:
        src: /config
        dest: ./
        flat: yes
      become: yes

    - name: Launching pods
      k8s:
        state: present
        kubeconfig: ./config
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: wordpress
          spec:
            containers:
              - name: wordpress
                image: wordpress:5.1.1-php-7.3-apache
      
