---
# tasks file for roles/common-dependencies-cluster

- name: Installing docker
  yum:
    name: docker
    state: present

- name: Yum repo for K8s
  yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: 
      - kubelet
      - kubeadm
      - kubectl

- name: Installing kubeadm, kubelet and kubectl
  yum:
    name: 
      - kubeadm
      - kubelet
      - kubectl 
    state: present
    disable_excludes: kubernetes

- name: Starting docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: configuring daemon.json
  copy:
      dest: "/etc/docker/daemon.json"
      src: daemon-docker

- name: Restarting docker services
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Enabling kubelet
  service:
    name: kubelet
    state: started
    enabled: yes